cityapp/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('add/', views.display_create_view, name='display_add'),
    path('<int:pk>/', views.display_update_view, name='display_change'),

    path('ajax/load-stations/', views.load_stations, name='ajax_load_stations'),  # AJAX
]

home/urls.py
from django.urls import path
from .import views

urlpatterns=[
    path('',views.home,name='home'),

]

project/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('cityapp/',include('cityapp.urls')),
    path('register/',include('register.urls')),
    path('',include('login.urls')),
    path('home',include('home.urls')),
]

cityapp/models.py
from django.db import models

# Create your models here.

class City(models.Model):
    cityname = models.CharField(max_length=40)

    def __str__(self):
        return self.cityname


class Stations(models.Model):
    city = models.ForeignKey(City, on_delete=models.CASCADE)
    stationname = models.CharField(max_length=40)

    def __str__(self):
        return self.stationname

class Bus(models.Model):
    time = models.CharField(max_length=150)
    bus = models.CharField(max_length=150)
    station = models.ForeignKey(Stations,on_delete=models.CASCADE)
    day = models.CharField(max_length=150,default="monday")
    timeinterval = models.CharField(max_length=25, default='8:00')

    def __str__(self):
        return f"{self.timeinterval}-{self.station}"

class Display(models.Model):

    cities = models.ForeignKey(City, on_delete=models.SET_NULL, blank=True, null=True)
    stations = models.ForeignKey(Stations, on_delete=models.SET_NULL, blank=True, null=True)
    day = models.CharField(max_length=125)
    time = models.CharField(max_length=25)

    def __str__(self):
        return f"{self.cities}-{self.stations}"

home/models.py
from django.db import models

# Create your models here.

cityapp/forms.py
from django import forms

from cityapp.models import Display, Stations


class DisplayCreationForm(forms.ModelForm):
    class Meta:
        model = Display
        fields = '__all__'
        exclude = ['timeinterval']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['stations'].queryset = Stations.objects.none()

        if 'cities' in self.data:
            try:
                city_id = int(self.data.get('cities'))
                self.fields['stations'].queryset = Stations.objects.filter(city_id=city_id).order_by('stationname')
            except (ValueError, TypeError):
                pass  # invalid input from the client; ignore and fallback to empty City queryset
        elif self.instance.pk:
            self.fields['stations'].queryset = self.instance.city.stations_set.order_by('stationname')

cityapp/views.py

from django.shortcuts import render

# Create your views here.
from django.http import JsonResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from .forms import DisplayCreationForm
from .models import Stations, Display, Bus


def display_create_view(request):
    form = DisplayCreationForm()
    if request.method == 'POST':
        form = DisplayCreationForm(request.POST)
        if form.is_valid():
            viewstations = form.cleaned_data['stations']
            viewtime = form.cleaned_data['time']
            viewday = form.cleaned_data['day']
            print(viewstations)

            bus = Bus()
            if Bus.objects.filter(station=viewstations).exists():
                data=Bus.objects.filter(station=viewstations) & Bus.objects.filter(time=viewtime) & Bus.objects.filter(day=viewday)



                return render(request,'cityapp/result.html',{'data':data})


            form.save()
            return redirect('display_add')
    return render(request, 'cityapp/home.html', {'form': form})


def display_update_view(request, pk):
    display = get_object_or_404(Display, pk=pk)
    form = DisplayCreationForm(instance=display)
    if request.method == 'POST':
        form = DisplayCreationForm(request.POST, instance=display)
        if form.is_valid():
            form.save()
            return redirect('display_change', pk=pk)
    return render(request, 'cityapp/home.html', {'form': form})


# AJAX
def load_stations(request):
    city_id = request.GET.get('city_id')
    stations = Stations.objects.filter(city_id=city_id).all()
    # return render(request, 'cityapp/city_dropdown_list_options.html', {'stations': stations})
    return JsonResponse(list(stations.values('id', 'stationname')), safe=False)

home/views.py
from django.shortcuts import render

# Create your views here.
def home(request):
    return render(request,'home/home.html')

cityapp/templates/cityapp/city_dropdown_list_options.html
<!--<option value="">-&#45;&#45;&#45;&#45;&#45;&#45;&#45;&#45;</option>-->
<!--{% for station in stations %}-->
<!--<option value="{{ station.pk }}">{{ station.stationname }}</option>-->
<!--{% endfor %}-->

cityapp/templates/cityapp/home.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Dependent Dropdown in Django</title>
    <style>

    <style>
        fieldset.scheduler-border {
    border: 1px groove #ddd !important;
    padding: 0 1.4em 1.4em 1.4em !important;
    margin: 0 0 1.5em 0 !important;
    -webkit-box-shadow:  0px 0px 0px 0px #000;
            box-shadow:  0px 0px 0px 0px #000;
                font-size: 1.2em !important;

    text-align: center !important

}

legend.scheduler-border {
    width: auto !important;
    font-size: 1.2em !important;
    font-weight: bold !important;
    text-align: center !important;
}
    </style>
</head>
<body>
<div>
{% include 'layout/signinheader.html' %}
</div>

<div
    class="p-5 text-center bg-image"
    style="
      background-image: url('/static/images/bg20.jpg');
      height: 400px;

    "
  >
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.1)">
      <div class="d-flex justify-content-center align-items-center h-100">




<div class="container-fluid">
<div class="search-box justify-content-center text-white ">
<form method="post" id="displayForm" data-stations-url="{% url 'ajax_load_stations' %}">
    {% csrf_token %}


        <legend class="scheduler-border">Find Your Bus</legend>
<!--    <h2>Find Yor Bus</h2>-->
    {{ form.as_p }}
    <input type="submit" value="Submit">

</form>
</div>
</div>
</div>
    </div>
    </div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_cities").change(function () {
        const url = $("#displayForm").attr("data-stations-url");  // get the url of the `load_cities` view
        const cityId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= /persons/ajax/load-cities/ )
            data: {
                'city_id': cityId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                console.log(data);
<!--                ("#id_stations").html(data); // replace the contents of the city input with the data that came from the server-->


                let html_data = '<option value="">---------</option>';
                data.forEach(function (station) {
                    html_data += `<option value="${station.id}">${station.stationname}</option>`
                });
                console.log(html_data);
                $("#id_stations").html(html_data);


            }
        });

    });
</script>

<div>
<footer>
    {% include 'layout/signin.html' %}
</footer>
</div>
</body>
</html>

cityapp/templates/cityapp/result.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js" integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js" integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG" crossorigin="anonymous"></script>
<link href="/your-path-to-fontawesome/css/fontawesome.css" rel="stylesheet">
    <title>Dependent Dropdown in Django</title>
</head>
<body>
<div>
{% include 'layout/signinheader.html' %}
</div>

<div class="container-fluid">


    <div
    class="p-5 text-center bg-image container-fluid"
    style="
      background-image: url('/static/images/bg18.jpg');
      height: 400px;
    "
  >
    <div class="mask" style="background-color: rgba(0, 0, 0, 0.1)">
      <div class="d-flex justify-content-center align-items-center h-100">

<div class="col result justify-content-lg-center d-flex">
<h1> Available bus</h1>
</div>
</div>
<div class="container-fluid">
    <div class="col-lg-12 text-dark justify-content-center d-flex flex-column ">
{% if data %}
    {% for bu in data %}

        <h6>Bus no:{{bu.bus}}</h6>
        <h6>Time:{{bu.timeinterval}}</h6>
        <h6>Place:{{bu.station}}</h6>

    {% endfor %}
{% else %}

    <h1>Soo Sorry </h1>
        <h2>There is no Bus at this time</h2>
        <h3> to travel you..</h3>
        <i class="far fa-meh-blank"></i>

{% endif %}

</div>
</div>
    </div>
    </div>



<!--<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">-->
<!--  <div class="carousel-indicators">-->
<!--    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>-->
<!--    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>-->
<!--    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>-->
<!--  </div>-->
<!--  <div class="carousel-inner">-->
<!--    <div class="carousel-item active">-->
<!--      <img src="{% static 'images/traffic.jpg' %}" class="d-block w-100" alt="...">-->
<!--      <div class="carousel-caption d-none d-md-block">-->
<!--        <h5>First slide label</h5>-->
<!--        <p>Some representative placeholder content for the first slide.</p>-->
<!--      </div>-->
<!--    </div>-->
<!--    <div class="carousel-item">-->
<!--      <img src="{% static 'images/gobus.jpg' %}" class="d-block w-100" alt="...">-->
<!--      <div class="carousel-caption d-none d-md-block">-->
<!--        <h5>Second slide label</h5>-->
<!--        <p>Some representative placeholder content for the second slide.</p>-->
<!--      </div>-->
<!--    </div>-->
<!--    <div class="carousel-item">-->
<!--      <img src="{% static 'images/road.jpeg' %}" class="d-block w-100" alt="...">-->
<!--      <div class="carousel-caption d-none d-md-block">-->
<!--        <h5>Third slide label</h5>-->
<!--        <p>Some representative placeholder content for the third slide.</p>-->
<!--      </div>-->
<!--    </div>-->
<!--  </div>-->
<!--  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="prev">-->
<!--    <span class="carousel-control-prev-icon" aria-hidden="true"></span>-->
<!--    <span class="visually-hidden">Previous</span>-->
<!--  </button>-->
<!--  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions"  data-bs-slide="next">-->
<!--    <span class="carousel-control-next-icon" aria-hidden="true"></span>-->
<!--    <span class="visually-hidden">Next</span>-->
<!--  </button>-->
<!--</div>-->



<footer>
    {% include 'layout/signin.html' %}
</footer>


</body>
</html>